---
###############################################################################
# COMMON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v1.3.0'

variables:
  CUSTOMER: 'coghent'
  APPLICATION: 'coghent-web-portal'
  TERRAFORM_IMAGE: 'web-terraform'
  TERRAFORM_TAG: 'latest'
  SKIP_DEPLOY: 'true'
